version: '3'
services:
  db:
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT_DEVELOPMENT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE_DEVELOPMENT}
      POSTGRES_USER: ${DB_USERNAME_DEVELOPMENT}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEVELOPMENT}
    env_file:
      - .env

  # TODO : FIX TEST DB
  db_test:
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT_TEST}:5433"
    environment:
      POSTGRES_DB: ${DB_DATABASE_TEST}
      POSTGRES_USER: ${DB_USERNAME_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
    env_file:
      - .env

  redis:
    build: ./redis
    ports:
      - "${REDIS_PORT_DEVELOPMENT}:6379"

  app:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    ports:
      - "${API_SERVER_PORT_DEVELOPMENT}:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/app
      - /usr/app/node_modules
    ports:
      - "${REACT_APP_PORT_DEVELOPMENT}:4000"
    depends_on:
      - app
    env_file:
      - .env
